# These tasks configure pulp/pulp_ansible so that we can use the container
# This will also reset pulp between iterations

# The pulp container has a long start up time
# The first task to interact with pulp needs to wait until it responds appropriately
- name: list pulp distributions
  uri:
    url: '{{ pulp_api }}/pulp/api/v3/distributions/ansible/ansible/'
    status_code:
      - 200
    user: '{{ pulp_user }}'
    password: '{{ pulp_password }}'
    force_basic_auth: true
  register: pulp_distributions
  until: pulp_distributions is successful
  delay: 1
  retries: 120

# A module is used to make the tests run quicker as this will send lots of API requests.
- name: reset pulp content
  reset_pulp:
    pulp_api: '{{ pulp_api }}'
    galaxy_api: '{{ galaxy_api }}'
    url_username: '{{ pulp_user }}'
    url_password: '{{ pulp_password }}'
    repository: published
    namespaces: '{{ namespaces|default([]) }}'
